### ISSUE TITLE
AUR: missing dependency

### ISSUE THREAD

**Issue by muttleyxd** [GabMus/HydraPaper#2]
_python-pilkit_ is required otherwise this happens:

```
Traceback (most recent call last):
  File "/usr/bin/hydrapaper", line 50, in <module>
    from hydrapaper import __main__
  File "/usr/lib/python3.6/site-packages/hydrapaper/__main__.py", line 29, in <module>
    from . import wallpaper_merger as WallpaperMerger
  File "/usr/lib/python3.6/site-packages/hydrapaper/wallpaper_merger.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

```

**Comment by GabMus** [comment]
fixed now
