### ISSUE TITLE
doesnt open

### ISSUE THREAD

**Issue by inikishev** [GabMus/HydraPaper#43]
```
bash-5.1$ hydrapaper
/usr/lib64/python3.10/site-packages/gi/types.py:217: Warning: cannot derive 'hydrapaper+main_stack+HydraPapaerMainStack' from final parent type 'AdwViewStack'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/usr/bin/hydrapaper", line 73, in <module>
    from hydrapaper import __main__
  File "/usr/lib/python3.10/site-packages/hydrapaper/__main__.py", line 6, in <module>
    from .app_window import HydraPaperAppWindow
  File "/usr/lib/python3.10/site-packages/hydrapaper/app_window.py", line 3, in <module>
    from .main_stack import HydraPapaerMainStack
  File "/usr/lib/python3.10/site-packages/hydrapaper/main_stack.py", line 6, in <module>
    class HydraPapaerMainStack(Adw.ViewStack):
  File "/usr/lib64/python3.10/site-packages/gi/types.py", line 226, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib64/python3.10/site-packages/gi/types.py", line 205, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib64/python3.10/site-packages/gi/types.py", line 217, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: hydrapaper+main_stack+HydraPapaerMainStack (subclass of AdwViewStack)
```

**Comment by antipodite** [comment]
I wrote a terminal alternative for Gnome 3, you could try this until the issues with HP are resolved: [Copic](https://github.com/antipodite/copic)

**Comment by inikishev** [comment]
> I wrote a terminal alternative for Gnome 3, you could try this until the issues with HP are resolved: [Copic](https://github.com/antipodite/copic)

thanks i dont have hp btw i have msi
